Repository wanted-august-8/matzip_rec, pull requests merged in 2024-08, with the labels that each got.

#27 Refactor: Modify DoSi Entity삭제
  src/main/java/com/matzip/api/matzip_api/domain/dosi/entity/DoSi.java
  src/main/java/com/matzip/api/matzip_api/domain/sgg/entity/Sgg.java
Labels: enhancement

#31 [Feature] #25 CICD 파이프라인 구성
  .github/workflows/deploy.yml
  appspec.yml
  build.gradle
  scripts/deploy.sh
  scripts/permit.sh
Labels: Feat

#34 [Feature] #25 cicd refactor
  .github/workflows/deploy.yml
  src/main/resources/application.yml
Labels: Feat

#37 Refactor #25 배포 관련 수정
  .github/workflows/deploy.yml
  appspec.yml
  scripts/deploy.sh
  src/main/resources/logback-prod.xml
Labels: Refactor
